### PR TITLE
Add HAR to JSON filetypes

### PR DESCRIPTION
**Pull request by wesinator**
### Description of the Change
Add [HTTP archive](https://w3c.github.io/web-performance/specs/HAR/Overview.html#sec-har) extension to the filetypes.

### CODE REVIEW

**Comment by lee-dohm** [comment]
Thanks for your contribution!

Because you can [customize how Atom recognizes files as specific languages](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition), we are only accepting extensions that are very common. Thanks again for your help and your passion for Atom!

**Comment by lee-dohm** [comment]
linguist has a different architecture than language recognition in Atom. Because it is a monolithic system, they can test all the permutations of language recognition collisions and ensure that the right language is chosen. But because Atom is an extensible architecture, adding an extension to a built-in language could prevent a package that a user has installed from using that extension simply because it is loaded first. So we have to be a bit more careful about adding extensions than linguist does.

**Comment by wesinator** [comment]
>  But because Atom is an extensible architecture, adding an extension to a built-in language could prevent a package that a user has installed from using that extension simply because it is loaded first. So we have to be a bit more careful about adding extensions than linguist does.

I understand that, but the only package that highlights .har is https://github.com/caleb531/language-har/blob/master/grammars/har.cson, which just loads this grammar.

**Comment by wesinator** [comment]
VS Code added `.har` to the json highlighting - https://github.com/microsoft/vscode/pull/77300

**Pull request closed without merging**
