### PR TITLE
Add .csslintrc to file types

### PR DESCRIPTION
**Pull request by silvenon**

### CODE REVIEW

**Comment by izuzak** [comment]
Thanks! :four_leaf_clover:

**Comment by silvenon** [comment]
Crap! My bad, I was hasty. `.csslintrc` is not JSON, as can be seen in CSSLint/csslint#568, `csslint.json` is, which will get JSON highlighting anyway.

Sorry :smiley:

**Comment by izuzak** [comment]
Oh wow, totally didn't know about that -- and I also checked at least a dozen of [those files on GitHub](https://github.com/search?l=&q=filename%3A.csslintrc&ref=advsearch&type=Code&utf8=%E2%9C%93) before merging, and all were JSON. 

Thanks for double-checking and letting us know. :tophat: Gonna revert it for now.

**Comment by izuzak** [comment]
Note: reverted the PR in https://github.com/atom/language-json/issues/16, unpublished the version of the package with this PR, and reverted the package upgrade in Atom.

**Comment by silvenon** [comment]
Yeah, it can be JSON, but there are two formats, so it's best not to assume.

**Pull request merged**
